kind: pipeline
name: docker

trigger:
  branch:
    - dev

platform:
  runner: 10.11.92.33

workspace:
  base: /go
  path: src/gitlab.wodcloud.com/cloud/yearning

volumes:
  - name: cache
    host:
      path: /data/cache/
  - name: go
    host:
      path: /data/cache/golang/pkg/
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: build-go
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-go-arch:1.16.7-alpine
    volumes:
      - name: go
        path: /go/pkg
    settings:
      binary: yearning
      main: cmd

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.13
      dockerfile: .beagle/Dockerfile
      repo: wod/yearning
      version: 'v2.3.5'
      channel: alpha-amd64
      args: 'TARGETOS=linux,TARGETARCH=amd64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.13-arm64
      dockerfile: .beagle/Dockerfile
      repo: wod/yearning
      version: 'v2.3.5'
      channel: alpha-arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.13-ppc64le
      dockerfile: .beagle/Dockerfile
      repo: wod/yearning
      version: 'v2.3.5'
      channel: alpha-ppc64le
      args: 'TARGETOS=linux,TARGETARCH=ppc64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:v1.2.3
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le
      template: registry.cn-qingdao.aliyuncs.com/wod/yearning:v2.3.5-alpha-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/yearning:v2.3.5-alpha
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: harbor

trigger:
  branch:
    - master

platform:
  runner: 10.11.92.33

workspace:
  base: /go
  path: src/gitlab.wodcloud.com/cloud/yearning

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: harbor-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/yearning:v2.3.5-alpha-amd64
      target: registry.cn-qingdao.aliyuncs.com/wod/yearning:v2.3.5-amd64
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/yearning:v2.3.5-alpha-arm64
      target: registry.cn-qingdao.aliyuncs.com/wod/yearning:v2.3.5-arm64
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/yearning:v2.3.5-alpha-ppc64le
      target: registry.cn-qingdao.aliyuncs.com/wod/yearning:v2.3.5-ppc64le
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:v1.2.3
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le
      template: registry.cn-qingdao.aliyuncs.com/wod/yearning:v2.3.5-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/yearning:v2.3.5
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - harbor-amd64
      - harbor-arm64
      - harbor-ppc64le

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: USERNAME
  path: devops-registry-aliyun

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: PASSWORD
  path: devops-registry-aliyun
